modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/TheIllusiveC4/Comforts/issues"
logoFile="${mod_icon}"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_url}"
authors="${mod_author}"
description='''
${mod_description}
'''
[[dependencies.comforts]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.comforts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13,1.14)"
    ordering="NONE"
side="BOTH"